### ISSUE TITLE
Test violations codes and docs

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/dotenv-linter#12]
We need to tests that all violations 

1. have unique codes
2. correctly sorted inside the code
3. have docs in the module docstrings

You can have a look at the example (this code can be even copy-pasted): https://github.com/wemake-services/wemake-python-styleguide/tree/master/tests/test_violations

**Comment by kaelscion** [comment]
Awesome! I'll get a look at it this week (super busy with a new contract).

**Comment by sobolevn** [comment]
Awesome! Thanks.

**Comment by kaelscion** [comment]
I've got the violations testing in order but noticed that we don't have a config.py for this project, unlike the example. In the example, the Configuration object is needed in the final function in test_docs.py to ensure that all documentation for all configurations is available. Is there an equivalent configuration file I should use for this instance that I just don't see or are we not using one?

**Comment by sobolevn** [comment]
Not yet. 🙁

**Comment by nifadyev** [comment]
Hello @sobolevn , are you interested in completing this issue? I may finish the work done in [this](https://github.com/wemake-services/dotenv-linter/pull/88) PR. It seems mostly done but needs some polishing.

**Comment by sobolevn** [comment]
Yes, please :)
