### ISSUE TITLE
pre-commit hooks support

### ISSUE THREAD

**Issue by KristobalJunta** [wemake-services/dotenv-linter#205]
Would be great for this tool to support the [Pre-commit tool](https://pre-commit.com/) hooks.
For this, a configuration file has to be added: https://pre-commit.com/#new-hooks

**Comment by sobolevn** [comment]
@KristobalJunta yes, that's a great idea! Do you want to help with this one?

**Comment by KristobalJunta** [comment]
@sobolevn actually, yes, I plan to look into this

**Comment by sobolevn** [comment]
Thanks a lot! Assigned.
