### ISSUE TITLE
release new version with updated click dependency

### ISSUE THREAD

**Issue by skarzi** [wemake-services/dotenv-linter#295]
Hi :wave:

Is it possible to release a new version of `dotenv-linter`?
Recently I have encountered a few issues related to the `click` version (`>=6.0,<7.0`) required by `dotenv-linter==0.1.5`.
It seems that `dotenv-linter` works perfectly also with `click>=7` - just look at [the latest `test` workflow run](https://github.com/wemake-services/dotenv-linter/runs/1405102384?check_suite_focus=true#step:6:62).

**Comment by sobolevn** [comment]
Yes, sure! We only need to fix https://github.com/wemake-services/dotenv-linter/issues/296

And I can release `0.2`

**Comment by skarzi** [comment]
super! So I can take care of #296 :+1:

**Comment by sobolevn** [comment]
Done.

**Comment by sobolevn** [comment]
Sorry for the long wait 👍

**Comment by skarzi** [comment]
thanks!
