### ISSUE TITLE
release a new dotenv-linter version

### ISSUE THREAD

**Issue by skarzi** [wemake-services/dotenv-linter#416]
Hi :wave: 

Could you release a new `dotenv-linter` version to PyPI? 
`0.2.0` has `click` pinned to `<8` which causes conflicts with a few other packages dependent on the newest `click` version (`8.0.3`)

Big thanks for developing and maintaining this project!

**Comment by sobolevn** [comment]
Will do soon! Thanks!

**Comment by sobolevn** [comment]
Done. Version `0.3.0` is released. Sorry for the long delay!

**Comment by sobolevn** [comment]
And thanks for your help 😊
