### ISSUE TITLE
Don't expect any particular casing convention

### ISSUE THREAD

**Issue by mcandre** [wemake-services/dotenv-linter#56]
While it is good for shell script authors to apply conventions of variable casing to distinguish between local and environment variables, this is unfortunately not a practical rule to use for environment variables in general.

Some applications have already begun to expect lowercase variable names (`http_proxy`), while other applications expect uppercase names (`HTTP_PROXY`). I wish a quick transition to a uniform standard would occur, but this has not been the case. So while the designer of a new environment-facing application should by all means prefer uppercase, we cannot reasonably apply a casing rule to .env files, because of the existing, mature exceptions.

Note that both lowercase *and* uppercase variables may be needed, for applications that need to apply proxy configurations to different sub-application calls. Hence, dotenv-linter should probably neither warn for duplicate variables as long as the declarations differ in casing.

**Comment by sobolevn** [comment]
Hey, @mcandre! Thanks for your feedback. 

This feature is planned for the next major release. I am planning to make an exception mechanism. Something similar to `noqa` in `flake8`. This will eliminate the need to reason about lower and uppercases. Just use `noqa` where you need to use lowercase variables for some reason.

Or disable this check completely via `--ignore` flag.

By the way, I invite you to collaborate on this feature. I would appreciate some help!

**Comment by sobolevn** [comment]
I am going to merge it with https://github.com/wemake-services/dotenv-linter/issues/31
