### ISSUE TITLE
Use safety

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/dotenv-linter#61]
Run the same in CI:
https://github.com/wemake-services/wemake-python-styleguide/blob/master/.travis.yml#L25-L27

**Comment by sobolevn** [comment]
We need to run `poetry run safety check --bare --full-report` inside the CI.
To do it we need to install `safety` as a dev-dependency: https://pypi.org/project/safety/

**Comment by sobolevn** [comment]
We can also run these two commands:

```yml
  - poetry check
  - poetry run pip check
```

They are required to check
1. that `pyproject.toml` and `poetry.lock` are valid (`poetry check`)
2. that current virtualenv is correct ( `pip check`)

**Comment by kaelscion** [comment]
I've submitted a pull request with the changes for this issue. Tests coverage is 98.12% after changes made, which is the same coverage as pre-changes. Let me know if you have any critiques, comments, or questions!

**Comment by sobolevn** [comment]
Awesome! Closed by #81
