### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by brunowego** [wemake-services/dotenv-linter#63]
# Rule request

Homebrew installation support, like:

```sh
brew install dotenv-linter
```

## Thesis

Many developers use homebrew as their primary tool for package management.

## Reasoning

Will be easy to engage more people to use.

**Comment by sobolevn** [comment]
Thanks a lot! That's on my list.
I guess that other platforms should also have a packaging option.

**Comment by Mr-Sunglasses** [comment]
> Thanks a lot! That's on my list. I guess that other platforms should also have a packaging option.

@sobolevn I'm working on homebrew support but the [dotenv-linter](https://github.com/wemake-services/dotenv-linter/issues/63#issuecomment-561554113) formula already exists on homebrew, maybe we can use any other name.

**Comment by sobolevn** [comment]
This one is a different one :) 
https://formulae.brew.sh/formula/dotenv-linter#default

**Comment by Mr-Sunglasses** [comment]
> This one is a different one :) https://formulae.brew.sh/formula/dotenv-linter#default

What I mean by this is that in homebrew no two formulas have the same name so either we have to do it as `brew install wemake-services/dotenv-linter` or `brew install dotenv_linter`

@sobolevn LMK which one is good or do any suggestions from your side?

**Comment by sobolevn** [comment]
`brew` won't allow `dotenv_linter`, I think this can be closed. This is a simple python script
