### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/dotenv-linter#80]
For future contributors `CONTRIBUTING.md` might be very useful.
Here are some examples:
- https://github.com/wemake-services/wemake-python-styleguide/blob/master/CONTRIBUTING.md
- https://github.com/mimesis-lab/pytest-mimesis/blob/master/CONTRIBUTING.md

**Comment by sobolevn** [comment]
@kaelscion please, share your experience with other contributors. Does these examples seem complete to you?

**Comment by kaelscion** [comment]
The python-styleguide CONTRIBUTING.md makes the most sense for the dotenv-linter. Do you mind if I use that one as a template for the CONTRIBUTING.md here?

**Comment by sobolevn** [comment]
Sure, feel free.

**Comment by kaelscion** [comment]
Sorry for the large amount of commits for the same file. I kept making small markdown errors and needed to fix them. All good now though!

**Comment by sobolevn** [comment]
Now we can start working on the main scope of the project. 

See https://github.com/wemake-services/dotenv-linter/issues/1
